[functions]
  node_bundler = "esbuild"
  external_node_modules = ["@aws-sdk/client-s3", "busboy"]

[dev]
  targetPort = 3000
  command = "yarn dev"

[functions.upload]
  timeout = 60

[build]
  command = "npm run build"
  publish = "dist"
  functions = "netlify/functions"
  environment = { NODE_VERSION = "22" }

# Scheduled function to process feedback and update the knowledge base daily
[[scheduled-functions]]
  function = "process-feedback"
  schedule = "@daily"

# Redirect all netlify function calls
[[redirects]]
  from = "/.netlify/functions/*"
  to = "/.netlify/functions/:splat"
  status = 200

# Single page app settings
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200 